### ISSUE TITLE
Address generation should support bech32 addresses

### ISSUE THREAD

**Issue by bucko13** [bpanel-org/bwallet#23]
UI doesn't seem to have an option for choosing which address format you would like to generate. I think this could be a very useful feature to have, especially for clarity on distinguishing between BCH and BTC addresses.

**Comment by bucko13** [comment]
Alternatively we could just decide that we want to prioritize bech32 and only show/generate those. Less steps for design/development, but loses flexibility.

**Comment by tynes** [comment]
This was recently merged in
